const data = {
  best_score: [
    {
      name: "Alvredo Vera Vetri",
      image: "images/peringkat/alvredo.png",
      true: 40,
      false: 0,
      no_ans: 0,
      total_score: 100,
    },
    {
      name: "Tatiana Franci",
      image: "images/peringkat/tatiana.png",
      true: 39,
      false: 1,
      no_ans: 0,
      total_score: 98,
    },
    {
      name: "Haylie Press",
      image: "images/peringkat/haylie.png",
      true: 35,
      false: 3,
      no_ans: 2,
      total_score: 90,
    },
    {
      name: "Jordin Siphero",
      image: "images/peringkat/jordin.png",
      true: 30,
      false: 5,
      no_ans: 5,
      total_score: 80,
    },
    {
      name: "Ruben Passandra",
      image: "images/peringkat/ruben.png",
      true: 30,
      false: 5,
      no_ans: 5,
      total_score: 80,
    },
    {
      name: "Maria Dias",
      image: "images/peringkat/maria.png",
      true: 29,
      false: 2,
      no_ans: 9,
      total_score: 78,
    },
    {
      name: "Reisa Stanford",
      image: "images/peringkat/reisa.png",
      true: 29,
      false: 1,
      no_ans: 10,
      total_score: 78,
    },
    {
      name: "Emerson Lengjsa",
      image: "images/peringkat/emerson.png",
      true: 27,
      false: 3,
      no_ans: 10,
      total_score: 74,
    },
    {
      name: "Haylie Kenter",
      image: "images/peringkat/haylie.png",
      true: 25,
      false: 10,
      no_ans: 5,
      total_score: 70,
    },
  ],
  story: [
    {
      name: "Marilyn Go",
      image: "images/story/marilyn.png",
    },
    {
      name: "Lydia Septian",
      image: "images/story/lydia.png",
    },
    {
      name: "Ahmad Gerald",
      image: "images/story/ahmad.png",
    },
    {
      name: "Jaylan Cang",
      image: "images/story/jaylan.png",
    },
    {
      name: "Ashlynn Ko",
      image: "images/story/ashlynn.png",
    },
    {
      name: "Skylar Carte",
      image: "images/story/skylar1.png",
    },
    {
      name: "Skylar Carte",
      image: "images/story/skylar2.png",
    },
    {
      name: "Skylar Carte",
      image: "images/story/skylar3.png",
    },
    {
      name: "Skylar Carte",
      image: "images/story/skylar4.png",
    },
    {
      name: "Skylar Carte",
      image: "images/story/skylar5.png",
    },
    {
      name: "Skylar Carte",
      image: "images/story/skylar6.png",
    },
    {
      name: "Skylar Carte",
      image: "images/story/skylar7.png",
    },
    {
      name: "Skylar Carte",
      image: "images/story/skylar8.png",
    },
    {
      name: "Skylar Carte",
      image: "images/story/skylar9.png",
    },
    {
      name: "Skylar Carte",
      image: "images/story/skylar10.png",
    },
    {
      name: "Skylar Carte",
      image: "images/story/skylar11.png",
    },
    {
      name: "Skylar Carte",
      image: "images/story/skylar12.png",
    },
    {
      name: "Alena May",
      image: "images/story/alena.png",
    },
    {
      name: "Craig Wong",
      image: "images/story/craig.png",
    },
    {
      name: "Talan Sip Huang",
      image: "images/story/talan.png",
    },
  ],
  course: [
    {
      title: "Desain Grafis",
      image: "images/course/desain.png",
      rating: 5,
      review: 20,
      store: "Course Hero",
      student: 203,
      teacher: 4,
      time: "7 Agustus 2020",
      price: 2000000,
      fix_price: 1500000,
    },
    {
      title: "Frontend Course",
      image: "images/course/frontend.png",
      rating: 4.5,
      review: 210,
      store: "Course Hero",
      student: 203,
      teacher: 4,
      time: "7 Agustus 2020",
      price: 2000000,
      fix_price: 1500000,
    },
    {
      title: "Piano",
      image: "images/course/piano.png",
      rating: 3.5,
      review: 34,
      store: "Course Hero",
      student: 203,
      teacher: 4,
      time: "7 Agustus 2020",
      price: 2000000,
      fix_price: 1500000,
    },
    {
      title: "IELTS",
      image: "images/course/ielts.png",
      rating: 5,
      review: 20,
      store: "Course Hero",
      student: 203,
      teacher: 4,
      time: "7 Agustus 2020",
      price: 2000000,
      fix_price: 1500000,
    },
    {
      title: "Violin",
      image: "images/course/violin.png",
      rating: 5,
      review: 20,
      store: "Course Hero",
      student: 203,
      teacher: 4,
      time: "7 Agustus 2020",
      price: 2000000,
      fix_price: 1500000,
    },
    {
      title: "TOEFL",
      image: "images/course/toefl.png",
      rating: 5,
      review: 20,
      store: "Course Hero",
      student: 203,
      teacher: 4,
      time: "7 Agustus 2020",
      price: 2000000,
      fix_price: 1500000,
    },
    {
      title: "UI/UX Design",
      image: "images/course/ui.png",
      rating: 5,
      review: 20,
      store: "Course Hero",
      student: 203,
      teacher: 4,
      time: "7 Agustus 2020",
      price: 2000000,
      fix_price: 1500000,
    },
    {
      title: "Fullstack Javascript",
      image: "images/course/fullstack.png",
      rating: 5,
      review: 20,
      store: "Course Hero",
      student: 203,
      teacher: 4,
      time: "7 Agustus 2020",
      price: 2000000,
      fix_price: 1500000,
    },
  ],
};

export default data;