import Head from "next/head";
import { CoursePreview, Navbar, Story, TopScore } from "../components";
import Statistics from "../components/molecules/Statistics";

export default function Home() {
  return (
    <div className="font-primary m-0 p-0 box-border">
      <Head>
        <title>STUDEXT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="shadow">
        <Navbar />
      </header>
      <main className="m-6">
        <div className="w-full">
          <div className="lg:flex">
            <div>
              <Story />
              <Statistics />
            </div>
            <div>
              <TopScore />
            </div>
          </div>
          <div>
            <CoursePreview />
          </div>
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
